{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-actuator",
    "version": "3.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator-autoconfigure",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.12.4"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-jakarta9",
          "version": {
            "requires": "1.12.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.2.4.jar",
          "url": "spring-boot-starter-actuator-3.2.4.jar",
          "size": 4805,
          "sha512": "13799cfb4f7dbe2c21f42cc1ded8194700c882b0c90621ec02bdd91368c8757d85d088bbb926771ab0604f00d6572cf63e29485d952fe70560e557c424ffebbe",
          "sha256": "3e99516e8586609186db24c1dffd74293c743f1cb68883f3526e1ec2018803bd",
          "sha1": "a26cd0ab56f912d2aa44504042af06f15d3d1a80",
          "md5": "f9199ecf6dea6b7ea79f07b2273de062"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator-autoconfigure",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.12.4"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-jakarta9",
          "version": {
            "requires": "1.12.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.2.4.jar",
          "url": "spring-boot-starter-actuator-3.2.4.jar",
          "size": 4805,
          "sha512": "13799cfb4f7dbe2c21f42cc1ded8194700c882b0c90621ec02bdd91368c8757d85d088bbb926771ab0604f00d6572cf63e29485d952fe70560e557c424ffebbe",
          "sha256": "3e99516e8586609186db24c1dffd74293c743f1cb68883f3526e1ec2018803bd",
          "sha1": "a26cd0ab56f912d2aa44504042af06f15d3d1a80",
          "md5": "f9199ecf6dea6b7ea79f07b2273de062"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.2.4.jar",
          "url": "spring-boot-starter-actuator-3.2.4.jar",
          "size": 4805,
          "sha512": "13799cfb4f7dbe2c21f42cc1ded8194700c882b0c90621ec02bdd91368c8757d85d088bbb926771ab0604f00d6572cf63e29485d952fe70560e557c424ffebbe",
          "sha256": "3e99516e8586609186db24c1dffd74293c743f1cb68883f3526e1ec2018803bd",
          "sha1": "a26cd0ab56f912d2aa44504042af06f15d3d1a80",
          "md5": "f9199ecf6dea6b7ea79f07b2273de062"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-actuator-maven-optional",
          "version": "3.2.4"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.2.4.jar",
          "url": "spring-boot-starter-actuator-3.2.4.jar",
          "size": 4805,
          "sha512": "13799cfb4f7dbe2c21f42cc1ded8194700c882b0c90621ec02bdd91368c8757d85d088bbb926771ab0604f00d6572cf63e29485d952fe70560e557c424ffebbe",
          "sha256": "3e99516e8586609186db24c1dffd74293c743f1cb68883f3526e1ec2018803bd",
          "sha1": "a26cd0ab56f912d2aa44504042af06f15d3d1a80",
          "md5": "f9199ecf6dea6b7ea79f07b2273de062"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-actuator-maven-optional",
          "version": "3.2.4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.2.4-javadoc.jar",
          "url": "spring-boot-starter-actuator-3.2.4-javadoc.jar",
          "size": 4744,
          "sha512": "ad4092d0ccd2ce7e849c637bc52dc609d37ad37a9f61b6a98c09a6a5b23b99b772a60f7f90a2c9320b8ea8d900a4382840c9bb30f47ff6683bcfdf58031a02dd",
          "sha256": "c80c991060677680737fca118ea8dfaa07fab1343e35e133931316eb905ad97a",
          "sha1": "0841dee23095777f1f34576327f8960ec7a84099",
          "md5": "541ce0ee2c55a87c2a8e0d733032bb41"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.2.4-sources.jar",
          "url": "spring-boot-starter-actuator-3.2.4-sources.jar",
          "size": 4743,
          "sha512": "efd1ae52d32f7fe45cecfc42e62c1021d37c1671248b78b8bb54f0b4b7ecf192f31fb0fab38551de7f91a6de6ccd2510a139cb81ba63e31359c498f9eb20bd5f",
          "sha256": "18a6ff6f70ab6469f81cdb35b747475094ea2e1bd37335af61734f551a855585",
          "sha1": "79c81c95dbffba7a12ee52f2e6367208208fe3c6",
          "md5": "6a9274d6c6c1fbeb2d888d12c09a15ac"
        }
      ]
    }
  ]
}
