{
  "formatVersion": "1.1",
  "component": {
    "group": "io.projectreactor",
    "module": "reactor-core",
    "version": "3.6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "reactor-core-3.6.4.jar",
          "url": "reactor-core-3.6.4.jar",
          "size": 1868826,
          "sha512": "b1df60029d32d8630b0ca9df2e0f1f72e7636f824b32a628ac79527469b96a2db3bb85b1faf1f99c9d8ae2d25c24f3e80c6ecc144f2e58e2cd7186fd1b4a93de",
          "sha256": "46ab18fce8c4834da85985bc01e6d37a52ec1c70d71946f1d66680abba304287",
          "sha1": "ef683486f29c4bbd1615abc5a83efc6bad8be871",
          "md5": "79680eaf93f21e6f51034ffdfcc48baa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "reactor-core-3.6.4.jar",
          "url": "reactor-core-3.6.4.jar",
          "size": 1868826,
          "sha512": "b1df60029d32d8630b0ca9df2e0f1f72e7636f824b32a628ac79527469b96a2db3bb85b1faf1f99c9d8ae2d25c24f3e80c6ecc144f2e58e2cd7186fd1b4a93de",
          "sha256": "46ab18fce8c4834da85985bc01e6d37a52ec1c70d71946f1d66680abba304287",
          "sha1": "ef683486f29c4bbd1615abc5a83efc6bad8be871",
          "md5": "79680eaf93f21e6f51034ffdfcc48baa"
        }
      ]
    }
  ]
}
